export const ACTIVATE_BLOCKER = "ACTIVATE_BLOCKER";
export const DEACTIVATE_BLOCKER = "DEACTIVATE_BLOCKER";
export const SET_BLACKLIST_MODE = "SET_BLACKLIST_MODE";
export const SET_WHITELIST_MODE = "SET_WHITELIST_MODE";
export const LOADING_MODEL = "LOADING_MODEL";
export const MODEL_LOAD_COMPLETE = "MODEL_LOAD_COMPLETE";
export const ERROR_LOADING_MODEL = "ERROR_LOADING_MODEL";
